version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pemilihan-db
    environment:
      POSTGRES_DB: vote
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gkjp2025
    volumes:
      - /root/vote/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pemilihan-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:Gkjp2025@db:5432/vote?sslmode=disable
      - VOTE_START=2025-08-18T08:00:00+07:00
      - VOTE_END=2025-08-20T23:00:00+07:00
      - ADMIN_USER=admin
      - ADMIN_PASS=Gkjp2025
      - PORT=8080
      - DEV=1
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: pemilihan-nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
